name: Test ifort

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 18 1-31/2 * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Run ifort tests
    runs-on: ${{ matrix.os }}
    # As of 20230117, we must set max-parallel to 50 (not higher) and put macos-x as the last os(es).
    # Otherwise, the other jobs will not start until all the macos jobs finish, which will take much
    # time since the maximal concurrent number of macos jobs is 5. See
    # https://support.github.com/ticket/personal/0/1952095
    strategy:
      fail-fast: false
      max-parallel: 50
      matrix:
        # Windows does not work. On Windows, the options for ifort/ifx starts with "/" instead of "-".
        os: [ubuntu-latest, macos-latest]
        ikind: [i2]
        solver: [cobyla]
        fflags: [-O1, -O2, -O3, -g, -fast]
        testdim: [small, big]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          submodules: recursive

      - name: Install Intel oneAPI on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/install_oneapi_linux.sh

      - name: Install Intel oneAPI on macOS
        if: startsWith(matrix.os, 'macos')
        run: bash .github/scripts/install_oneapi_macos.sh

      - name: Miscellaneous setup
        shell: bash
        run: bash .github/scripts/misc_setup

      - name: Conduct the test
        shell: bash
        run: |
          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./flint --all && bash ./mlint --all
          cd "$ROOT_DIR"/fortran/tests
          $SEDI 's|800|100|g' test_*.f90
          if [[ -f "test_uobyqa.f90" ]] ; then
              $SEDI 's|bign = 120|bign = 90|g' test_uobyqa.f90
          fi
          if [[ -f "test_cobyla.f90" ]] ; then
              $SEDI 's|bign = 120|bign = 90|g' test_cobyla.f90
          fi
          if [[ -f "test_bobyqa.f90" ]] ; then
              $SEDI 's|bign = 400|bign = 380|g' test_bobyqa.f90
          fi
          export FFLAGS=${{ matrix.fflags }} && export TESTDIM=${{ matrix.testdim }} && make itest_${{ matrix.ikind }}.${{ matrix.solver }}
          cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }} && make itest

      - name: Store artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run: rm -rf ${{ env.TEST_DIR }}
